// src/playlist.js
const playlist1 = [
  {
    id: 1,
    scale: "minor",
    key: "D",
    tempo: 140,
    title: "O.G Lover",
    artist: "Jukka & O.G",
    src: "/audio/track1.mp3",
  },
  {
    id: 2,
    scale: "major",
    key: "C",
    tempo: 132,
    title: "HFlee",
    artist: "Silverman",
    src: "/audio/track2.mp3",
  },
  {
    id: 3,
    scale: "minor",
    key: "F",
    tempo: 76,
    title: "€gyptian",
    artist: "Jukka",
    src: "/audio/track3.mp3",
  },
  {
    id: 4,
    scale: "minor",
    key: "E",
    tempo: 81,
    title: "1000s",
    artist: "Jukka",
    src: "/audio/track4.mp3",
  },
  {
    id: 5,
    scale: "minor",
    key: "C",
    tempo: 135,
    title: "Babylon",
    artist: "Jukka",
    src: "/audio/track5.mp3",
  },
  {
    id: 6,
    scale: "minor",
    key: "E",
    tempo: 138,
    title: "Bankov",
    artist: "Jukka",
    src: "/audio/track6.mp3",
  },
  {
    id: 7,
    scale: "minor",
    key: "B♭",
    tempo: 80,
    title: "CreamTrunk",
    artist: "Jukka",
    src: "/audio/track7.mp3",
  },
  {
    id: 8,
    scale: "major",
    key: "D",
    tempo: 122,
    title: "LunaHD",
    artist: "Jukka",
    src: "/audio/track8.mp3",
  },
  {
    id: 9,
    scale: "major",
    key: "C",
    tempo: 138,
    title: "Ligma",
    artist: "Jukka",
    src: "/audio/track9.mp3",
  },
  {
    id: 10,
    scale: "major",
    key: "B♭",
    tempo: 115,
    title: "Summy",
    artist: "Jukka",
    src: "/audio/track10.mp3",
  },
  {
    id: 11,
    scale: "minor",
    key: "F#",
    tempo: 146,
    title: "Babie",
    artist: "Jukka",
    src: "/audio/track11.mp3",
  },
  {
    id: 12,
    scale: "minor",
    key: "D",
    tempo: 136,
    title: "Santiago",
    artist: "Jukka",
    src: "/audio/track12.mp3",
  },
  {
    id: 13,
    scale: "minor",
    key: "C#",
    tempo: 139,
    title: "Galyaah",
    artist: "Jukka",
    src: "/audio/track13.mp3",
  },
  {
    id: 14,
    scale: "minor",
    key: "D",
    tempo: 126,
    title: "Drainer",
    artist: "Jukka",
    src: "/audio/track14.mp3",
  },
  {
    id: 15,
    scale: "major",
    key: "B",
    tempo: 150,
    title: "Cuibk",
    artist: "Jukka",
    src: "/audio/track15.mp3",
  },
];
const playlist2 = [
  {
    id: 16,
    scale: "minor",
    key: "C",
    tempo: 125,
    title: "Dring",
    artist: "Jukka",
    src: "/audio/track16.mp3",
  },
  {
    id: 17,
    scale: "minor",
    key: "D",
    tempo: 143,
    title: "cWhat",
    artist: "Jukka",
    src: "/audio/track17.mp3",
  },
  {
    id: 18,
    scale: "minor",
    key: "C#",
    tempo: 80,
    title: "cDawg",
    artist: "Jukka",
    src: "/audio/track18.mp3",
  },
  {
    id: 19,
    scale: "minor",
    key: "A",
    tempo: 125,
    title: "Story",
    artist: "Jukka",
    src: "/audio/track19.mp3",
  },
  {
    id: 20,
    scale: "minor",
    key: "C#",
    tempo: 128,
    title: "Xtra",
    artist: "Jukka",
    src: "/audio/track20.mp3",
  },
  {
    id: 21,
    scale: "major",
    key: "E",
    tempo: 140,
    title: "Yushi",
    artist: "Jukka",
    src: "/audio/track21.mp3",
  },
  {
    id: 22,
    scale: "minor",
    key: "E♭",
    tempo: 73,
    title: "Maomam",
    artist: "Jukka",
    src: "/audio/track22.mp3",
  },
  {
    id: 23,
    scale: "minor",
    key: "F#",
    tempo: 80,
    title: "Mymsg",
    artist: "Jukka",
    src: "/audio/track23.mp3",
  },
  {
    id: 24,
    scale: "major",
    key: "C",
    tempo: 139,
    title: "Magnolee",
    artist: "Jukka",
    src: "/audio/track24.mp3",
  },
  {
    id: 25,
    scale: "major",
    key: "A♭",
    tempo: 80,
    title: "Swang",
    artist: "Jukka",
    src: "/audio/track25.mp3",
  },
  {
    id: 26,
    scale: "major",
    key: "D",
    tempo: 152,
    title: "Glitchmafia",
    artist: "Jukka",
    src: "/audio/track26.mp3",
  },
  {
    id: 27,
    scale: "minor",
    key: "F#",
    tempo: 115,
    title: "Jangu ",
    artist: "Jukka",
    src: "/audio/track27.mp3",
  },
  {
    id: 28,
    scale: "minor",
    key: "C",
    tempo: 133,
    title: "zoooLyfe pt1",
    artist: "Jukka",
    src: "/audio/track28.mp3",
  },
  {
    id: 29,
    scale: "minor",
    key: "F",
    tempo: 138,
    title: "zoooLyfe pt2",
    artist: "Jukka",
    src: "/audio/track28.mp3",
  },
  {
    id: 30,
    scale: "minor",
    key: "F#",
    tempo: 130,
    title: "zoooLyfe pt3",
    artist: "Jukka",
    src: "/audio/track28.mp3",
  },
];

export { playlist1, playlist2 };
