// src/playlist.js
export const playlist= [
  {
    id: 1,
    scale: "minor",
    key: "D",
    tempo: 140,
    title: "O.G Lover",
    artist: "Jukka & O.G",
    src: "/audio/track1.mp3",
  },
  {
    id: 2,
    scale: "major",
    key: "C",
    tempo: 132,
    title: "HFlee",
    artist: "Silverman",
    src: "/audio/track2.mp3",
  },
  {
    id: 3,
    scale: "minor",
    key: "F",
    tempo: 76,
    title: "€gyptian",
    artist: "Jukka",
    src: "/audio/track3.mp3",
  },
  {
    id: 4,
    scale: "minor",
    key: "E",
    tempo: 81,
    title: "1000s",
    artist: "Jukka",
    src: "/audio/track4.mp3",
  },
  {
    id: 5,
    scale: "minor",
    key: "C",
    tempo: 135,
    title: "Babylon",
    artist: "Jukka",
    src: "/audio/track5.mp3",
  },
  {
    id: 6,
    scale: "minor",
    key: "E",
    tempo: 138,
    title: "Bankov",
    artist: "Jukka",
    src: "/audio/track6.mp3",
  },
  {
    id: 7,
    scale: "minor",
    key: "B♭",
    tempo: 80,
    title: "CreamTrunk",
    artist: "Jukka",
    src: "/audio/track7.mp3",
  },
  {
    id: 8,
    scale: "major",
    key: "D",
    tempo: 122,
    title: "LunaHD",
    artist: "Jukka",
    src: "/audio/track8.mp3",
  },
  {
    id: 9,
    scale: "major",
    key: "C",
    tempo: 138,
    title: "Ligma",
    artist: "Jukka",
    src: "/audio/track9.mp3",
  },
  {
    id: 10,
    scale: "major",
    key: "B♭",
    tempo: 115,
    title: "Summy",
    artist: "Jukka",
    src: "/audio/track10.mp3",
  },
  {
    id: 11,
    scale: "minor",
    key: "F#",
    tempo: 146,
    title: "Babie",
    artist: "Jukka",
    src: "/audio/track11.mp3",
  },
  {
    id: 12,
    scale: "minor",
    key: "D",
    tempo: 136,
    title: "Santiago",
    artist: "Jukka",
    src: "/audio/track12.mp3",
  },
  {
    id: 13,
    scale: "minor",
    key: "C#",
    tempo: 139,
    title: "Galyaah",
    artist: "Jukka",
    src: "/audio/track13.mp3",
  },
  {
    id: 14,
    scale: "minor",
    key: "D",
    tempo: 126,
    title: "Drainer",
    artist: "Jukka",
    src: "/audio/track14.mp3",
  },
  {
    id: 15,
    scale: "major",
    key: "B",
    tempo: 150,
    title: "Cuibk",
    artist: "Jukka",
    src: "/audio/track15.mp3",
  },
];
